### PR TITLE
Support Null values, Fix Types and other bugs

### PR DESCRIPTION
**Pull request by nmn**
The overall changes here are small, but still I've ended up changing a few things.

## Configs
I moved the `.config` files to the project root, although the only reason that I did this was to make VS Code plugins work for me. If you feel strongly, I can move them back to the config folder.

## Rely on Babel
I saw that you were creating an arguments array manually for speed. I switched this to the `...styles` rest param and added "@babel/plugin-transform-parameters", which achieves the same thing but makes it easier to define types for the function consistently.

In one other location, I used de-structuring for a cacheEntry, which also gets transpiled away by Babel.

## Update Flow
I know that you eventually want to change the codebase to Typescript. But in the meantime, I've upgraded to the newest version of Flow, improved coverage and generally fixed type errors.

## Different cache per configuration
There was one global `cache` being used so far. However, this would lead to bugs if different `styleq` instances were created by passing different configurations to the factory function.

I've fixed this by moving the cache inside the factory function. Once the `styleq` instance is created, it will keep using the same instance by closure anyway.

## Track keys that have a non-string value
Now I'm getting to the *real* problem that I wanted to fix. There was code that looked like this:

```js
if (typeof value === 'string') {
  if (!definedProperties.includes(prop)) {
    ...
  }
}
```

This ignored any keys that did not have a `string` value. *Firstly*, this also needs to support `null` values. But also, even though values of other types can be ignored, the keys need to be tracked as even invalid values will override previously defined values.

I'm sure about `null` as that's a feature in both stylex and React Native and should be supported. For other non-string, non-null values, the new behaviour should match React Native AFAIKT.

### CODE REVIEW

**Comment by nmn** [comment]
## Update - Type definition files

I've updated the project to export type definitions for both Flow and Typescript.

Flow will automatically choose `stylex.js.flow` over `stylex.js` when available in the same locations.

Typescript will look at the `"types"` field in `package.json`

As long as the `src` folder is part of the NPM package the types should work correctly.

**Comment by necolas** [comment]
This PR has too many unrelated changes. Please revert changes to config file locations, addition of Babel transforms, and break everything else you want to propose down into individual PRs

**Comment by necolas** [comment]
Changes to the logic, and bug fixes, should have corresponding unit tests as well

**Comment by nmn** [comment]
I'll split this into a few different PRs. Thanks for the quick review.

**Pull request closed without merging**
